services:

  server:
    build:
      context: .
      target: final
    ports:
      - 8001:8000
    env_file:
      - .env.docker
    depends_on:
      database:
        condition: service_healthy


  database:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env.docker
    ports:
      - "5431:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  db-data:

